### ISSUE TITLE
Debug-output stops, but still working hikvision-node

### ISSUE THREAD

**Issue by ozett** [henry-spanka/node-red-contrib-hikvision#11]
i checked my logs this morning an the debug-output from a hikvision-node stopped yesterday,
but it was still functional.

something to investigage?

i will try to log to files over a longer period and will report if there are more details to check.

![image](https://user-images.githubusercontent.com/5937811/68083092-0acd9100-fe25-11e9-97ba-0b5bda36c2c9.png)
----Update:
i switched my node-red starting from within "screen" and verbose-logging to systemctl and syslog-logging (https://raw.githubusercontent.com/node-red/linux-installers/master/resources/nodered.service) and will now check if this effec occurs again. i will report here)

**Comment by henry-spanka** [comment]
Hmm, I don't know. Maybe only a node died. I'm not sure if these issues are logged somewhere.

**Comment by ozett** [comment]
maybe debug output stop with energy-save of workstation or browser. 
think i dont investigate this. maybe come back here it i have an actual problem again 
thx

**Comment by henry-spanka** [comment]
👍 Feel free to reopen this issue the problem still exists.
