### ISSUE TITLE
Getting an error - Cannot install the node

### ISSUE THREAD

**Issue by smarthkapoor** [henry-spanka/node-red-contrib-hikvision#2]
Hi I am making a node red implementation and trying to host it on my Raspberry Pi. I am trying to add my HIKVision camera feed into my dashboard, but when i try and install this, I get the following error: 

C:\Users\*****>npm install node-red-contrib-hikvision
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\*****\package.json'
npm WARN ***** No description
npm WARN ***** No repository field.
npm WARN ***** No README data
npm WARN ***** No license field.

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for net-keepalive@0.3.8: wanted {"os":"darwin,linux,!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux,!win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*****\AppData\Roaming\npm-cache\_logs\2019-05-27T04_18_06_075Z-debug.log.

I have tried instlling this on my windows laptop aswell but same issue. I definately need to use my Pi for this, what can I do?

**Comment by henry-spanka** [comment]
Hi,
the plugin only supports linux because some dependencies only support linux. Note that its currently not supported to get the video stream. Only motion detection notifications and a snapshot of the camera image. But you should be able to use other plugins in combination with rtsp protocol to do this.

**Comment by henry-spanka** [comment]
You can try to install it again on Windows. I haven't tested it yet but as far as I can tell no dependencies require Linux only now so it might work.

**Comment by xyz8858** [comment]
Hi,

Still having this same issue as above.

Using full Ubuntu as Node Red server.
