### ISSUE TITLE
Camera showing disconnected

### ISSUE THREAD

**Issue by l19mxb** [henry-spanka/node-red-contrib-hikvision#35]
I would like to receive alarms from my camera, but i am unable to get the camera connected.

The credentials are ok, and once camera connects i am confident the alarms have been configured properly.

Any ideas why the camera shows "disconected"?

![Pi Settings Hik Camera](https://user-images.githubusercontent.com/49220201/89365687-80e68780-d718-11ea-8515-27e1c2af9aa2.png)
![Hik Camera](https://user-images.githubusercontent.com/49220201/89365700-85ab3b80-d718-11ea-81a7-b2b3a682f1fa.png)
![Hik Camera model](https://user-images.githubusercontent.com/49220201/89365704-880d9580-d718-11ea-9a51-26f00871d6da.png)

**Comment by ozett** [comment]
reset camera? reset/restart  node-red?
check if you filled in port 80 of the camera credentials ? even if there was numbers to see... check, pleases..
check if your enabled all protocols in camera. for hints see this thread -> https://github.com/henry-spanka/node-red-contrib-hikvision/issues/31

**Comment by l19mxb** [comment]
Thanks @ozett 

The article #31 helped me find the issue! It was the "WEB Authentication"

Set to digest/basic - Now we are connected!
![image](https://user-images.githubusercontent.com/49220201/89476678-b3eb5280-d7ce-11ea-99b2-c5981e022fe1.png)

![image](https://user-images.githubusercontent.com/49220201/89476659-acc44480-d7ce-11ea-8e4c-ddbeadb411ba.png)

**Comment by ozett** [comment]
Great ! glad you got i working 💐

**Comment by henry-spanka** [comment]
👍 Closing this now
