### ISSUE TITLE
auth not working

### ISSUE THREAD

**Issue by ozett** [henry-spanka/node-red-contrib-hikvision#5]
i provided user-credentials,
but i got an connection error..

how to debug this further?
(thx)

cam and firmware:
![image](https://user-images.githubusercontent.com/5937811/67697192-75577a80-f9a8-11e9-8f6e-01b70655ed9d.png)

credntials in node-red:
![image](https://user-images.githubusercontent.com/5937811/67697328-a89a0980-f9a8-11e9-82fd-865f40f007f3.png)

**Comment by henry-spanka** [comment]
Hmm. Can you manually reach the camera from your server? Try with: `curl http://192.168.14.117`

Check that System -> Security -> Authentication is set to digest/basic (RTSP and Web) and Network -> Advanced Settings -> Integration Protocol -> Enable Hikvision-CGI is checked and set to digest/basic.

**Comment by ozett** [comment]
now seems to work. sorry, more or less my fault..

i had for testing also node-hikamera installed.
(https://github.com/dbowerman/node-red-contrib-hikcamera)

i removed that ..now the error is also gone...
(maybe one cannot use both modules together...)

thx for now

**Comment by ozett** [comment]
i think the pre-written portnumber (80) in the auth-credentials also made me think,
i could leave this empty, because 80 is use than as default.

but as i tried with a second camera, i had an error again.
i started with a new node and filled in explicit the portnumer.
🎉 
no more error on this... 
i now go on an check the debug log to grab some smart-events from line-crossing and see how that works..

thx a lot so far,
😜

**Comment by henry-spanka** [comment]
I think you're on to something here. I will fix that right away.

**Comment by henry-spanka** [comment]
fixed in 58a6c1bcb4775a20fc7a57a7cd796da53a360933

Please let me know if it works.

**Comment by ozett** [comment]
as i installed with cli, i am a little bit off the track how i update this to your fixed-version.
npm update...? or simply again "npm install.."... #...?

maybe a hint from you for the right cli-syntax?

😉

**Comment by henry-spanka** [comment]
Just do `npm install henry-spanka/node-red-contrib-hikvision#master` again

**Comment by ozett** [comment]
thx, i did it here .... https://github.com/henry-spanka/node-red-contrib-hikvision/issues/4#issuecomment-547116001

install looks like success

**Comment by henry-spanka** [comment]
👍 I will close this issue now.
